sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t danielcosteira/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true danielcosteira/docker-react npm run test